--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

-- Started on 2021-06-02 17:33:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 24855)
-- Name: cities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cities (
    id integer NOT NULL,
    name character varying(75) NOT NULL,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    created_at date DEFAULT CURRENT_DATE
);


ALTER TABLE public.cities OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 24853)
-- Name: cities_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 33112)
-- Name: cv_cover_letters; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_cover_letters (
    id integer NOT NULL,
    content character varying NOT NULL,
    created_at date DEFAULT CURRENT_DATE,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    jobseeker_id integer NOT NULL
);


ALTER TABLE public.cv_cover_letters OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 33110)
-- Name: cover_letters_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cv_cover_letters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cover_letters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 33048)
-- Name: cv_experiences; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_experiences (
    id integer NOT NULL,
    working_place character varying(200) NOT NULL,
    "position" character varying(200) NOT NULL,
    start_at date NOT NULL,
    end_at date,
    created_at date DEFAULT CURRENT_DATE,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    jobseeker_id integer NOT NULL
);


ALTER TABLE public.cv_experiences OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 33055)
-- Name: cv_foreign_languages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_foreign_languages (
    id integer NOT NULL,
    language character varying NOT NULL,
    level integer NOT NULL,
    created_at date DEFAULT CURRENT_DATE,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    jobseeker_id integer NOT NULL
);


ALTER TABLE public.cv_foreign_languages OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 33286)
-- Name: cv_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_images (
    id integer NOT NULL,
    url character varying NOT NULL,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    created_at date DEFAULT CURRENT_DATE,
    jobseeker_id integer NOT NULL,
    jobseeker_user_id integer
);


ALTER TABLE public.cv_images OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 33284)
-- Name: cv_images_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cv_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cv_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 33065)
-- Name: cv_links; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_links (
    id integer NOT NULL,
    url character varying NOT NULL,
    created_at date DEFAULT CURRENT_DATE,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    name character varying NOT NULL,
    jobseeker_id integer NOT NULL
);


ALTER TABLE public.cv_links OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 33063)
-- Name: cv_links_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cv_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cv_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 33075)
-- Name: cv_programming_skills; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_programming_skills (
    id integer NOT NULL,
    skill_name character varying(100) NOT NULL,
    created_at date DEFAULT CURRENT_DATE,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    jobseeker_id integer NOT NULL
);


ALTER TABLE public.cv_programming_skills OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 33082)
-- Name: cv_schools; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_schools (
    id integer NOT NULL,
    name character varying(300) NOT NULL,
    department character varying(200) NOT NULL,
    start_at date NOT NULL,
    end_at date,
    created_at date DEFAULT CURRENT_DATE,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    jobseeker_id integer NOT NULL
);


ALTER TABLE public.cv_schools OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 33080)
-- Name: cv_schools_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cv_schools ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cv_schools_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 203 (class 1259 OID 16592)
-- Name: employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees (
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL
);


ALTER TABLE public.employees OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 16580)
-- Name: employers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employers (
    user_id integer NOT NULL,
    website character varying(250) NOT NULL,
    phone_number character varying(30) NOT NULL,
    is_verified boolean NOT NULL,
    company_name character varying(250) NOT NULL
);


ALTER TABLE public.employers OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 24773)
-- Name: verification_codes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.verification_codes (
    id integer NOT NULL,
    user_id integer NOT NULL,
    code character varying(50) NOT NULL,
    is_confirmed boolean NOT NULL,
    created_at date DEFAULT CURRENT_DATE,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false
);


ALTER TABLE public.verification_codes OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 24771)
-- Name: employers_verification_codes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.verification_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employers_verification_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 24780)
-- Name: employers_verification_employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employers_verification_employees (
    id integer NOT NULL,
    employer_id integer NOT NULL,
    employee_id integer NOT NULL,
    created_at date DEFAULT CURRENT_DATE NOT NULL
);


ALTER TABLE public.employers_verification_employees OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 24778)
-- Name: employers_verification_employees_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employers_verification_employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employers_verification_employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 33046)
-- Name: experiences_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cv_experiences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.experiences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 33053)
-- Name: foreign_languages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cv_foreign_languages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.foreign_languages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 16642)
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hibernate_sequence OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 24845)
-- Name: job_adverts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_adverts (
    id integer NOT NULL,
    job_position_id integer NOT NULL,
    description character varying NOT NULL,
    city_id integer NOT NULL,
    open_position_count integer NOT NULL,
    deadline date NOT NULL,
    is_open boolean,
    created_at date NOT NULL,
    is_active boolean,
    is_deleted boolean,
    employer_id integer NOT NULL,
    published_at date NOT NULL,
    salary_min integer,
    salary_max integer
);


ALTER TABLE public.job_adverts OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 24843)
-- Name: job_adverts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job_adverts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_adverts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 24592)
-- Name: job_positions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_positions (
    id integer NOT NULL,
    job_title character varying(150) NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean
);


ALTER TABLE public.job_positions OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 24590)
-- Name: job_positions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job_positions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_positions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 201 (class 1259 OID 16569)
-- Name: jobseekers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jobseekers (
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    national_id character varying(11) NOT NULL,
    is_verified boolean DEFAULT false NOT NULL,
    date_of_birth date NOT NULL
);


ALTER TABLE public.jobseekers OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 33073)
-- Name: programming_skills_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cv_programming_skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.programming_skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 200 (class 1259 OID 16564)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(30) NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 16616)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2993 (class 2606 OID 24859)
-- Name: cities cities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);


--
-- TOC entry 3005 (class 2606 OID 33122)
-- Name: cv_cover_letters cover_letters_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_cover_letters
    ADD CONSTRAINT cover_letters_pkey PRIMARY KEY (id);


--
-- TOC entry 3007 (class 2606 OID 33296)
-- Name: cv_images cv_images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_images
    ADD CONSTRAINT cv_images_pkey PRIMARY KEY (id);


--
-- TOC entry 2999 (class 2606 OID 33072)
-- Name: cv_links cv_links_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_links
    ADD CONSTRAINT cv_links_pkey PRIMARY KEY (id);


--
-- TOC entry 3003 (class 2606 OID 33089)
-- Name: cv_schools cv_schools_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_schools
    ADD CONSTRAINT cv_schools_pkey PRIMARY KEY (id);


--
-- TOC entry 2983 (class 2606 OID 16599)
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (user_id);


--
-- TOC entry 2981 (class 2606 OID 16589)
-- Name: employers employers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers
    ADD CONSTRAINT employers_pkey PRIMARY KEY (user_id);


--
-- TOC entry 2987 (class 2606 OID 24777)
-- Name: verification_codes employers_verification_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_codes
    ADD CONSTRAINT employers_verification_codes_pkey PRIMARY KEY (id);


--
-- TOC entry 2989 (class 2606 OID 24784)
-- Name: employers_verification_employees employers_verification_employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers_verification_employees
    ADD CONSTRAINT employers_verification_employees_pkey PRIMARY KEY (id);


--
-- TOC entry 2995 (class 2606 OID 33052)
-- Name: cv_experiences experiences_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_experiences
    ADD CONSTRAINT experiences_pkey PRIMARY KEY (id);


--
-- TOC entry 2997 (class 2606 OID 33062)
-- Name: cv_foreign_languages foreign_languages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_foreign_languages
    ADD CONSTRAINT foreign_languages_pkey PRIMARY KEY (id);


--
-- TOC entry 2991 (class 2606 OID 24852)
-- Name: job_adverts job_adverts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_adverts
    ADD CONSTRAINT job_adverts_pkey PRIMARY KEY (id);


--
-- TOC entry 2985 (class 2606 OID 24596)
-- Name: job_positions job_positions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_positions
    ADD CONSTRAINT job_positions_pkey PRIMARY KEY (id);


--
-- TOC entry 2977 (class 2606 OID 24810)
-- Name: jobseekers jobseekers_national_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobseekers
    ADD CONSTRAINT jobseekers_national_id_key UNIQUE (national_id) INCLUDE (national_id);


--
-- TOC entry 2979 (class 2606 OID 16591)
-- Name: jobseekers jobseekers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobseekers
    ADD CONSTRAINT jobseekers_pkey PRIMARY KEY (user_id);


--
-- TOC entry 3001 (class 2606 OID 33079)
-- Name: cv_programming_skills programming_skills_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_programming_skills
    ADD CONSTRAINT programming_skills_pkey PRIMARY KEY (id);


--
-- TOC entry 3009 (class 2606 OID 33339)
-- Name: cv_images uk_oxr4t115vjkx8mtlwi984qxbj; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_images
    ADD CONSTRAINT uk_oxr4t115vjkx8mtlwi984qxbj UNIQUE (jobseeker_user_id);


--
-- TOC entry 3011 (class 2606 OID 33341)
-- Name: cv_images uk_t9k5o9uta40uhd6tvgobc5h9h; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_images
    ADD CONSTRAINT uk_t9k5o9uta40uhd6tvgobc5h9h UNIQUE (jobseeker_id);


--
-- TOC entry 2973 (class 2606 OID 24812)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email) INCLUDE (email);


--
-- TOC entry 2975 (class 2606 OID 16568)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3019 (class 2606 OID 24865)
-- Name: job_adverts city_fk_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_adverts
    ADD CONSTRAINT city_fk_id FOREIGN KEY (city_id) REFERENCES public.cities(id) NOT VALID;


--
-- TOC entry 3016 (class 2606 OID 24823)
-- Name: employers_verification_employees employee_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers_verification_employees
    ADD CONSTRAINT employee_id FOREIGN KEY (employee_id) REFERENCES public.employees(user_id) NOT VALID;


--
-- TOC entry 3020 (class 2606 OID 24870)
-- Name: job_adverts employer_fk_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_adverts
    ADD CONSTRAINT employer_fk_id FOREIGN KEY (employer_id) REFERENCES public.employers(user_id) NOT VALID;


--
-- TOC entry 3017 (class 2606 OID 24828)
-- Name: employers_verification_employees employer_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers_verification_employees
    ADD CONSTRAINT employer_id FOREIGN KEY (employer_id) REFERENCES public.employers(user_id) NOT VALID;


--
-- TOC entry 3028 (class 2606 OID 33333)
-- Name: cv_images fk45mkhvcre9qc8y099tmcrxot3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_images
    ADD CONSTRAINT fk45mkhvcre9qc8y099tmcrxot3 FOREIGN KEY (jobseeker_user_id) REFERENCES public.jobseekers(user_id);


--
-- TOC entry 3018 (class 2606 OID 24860)
-- Name: job_adverts job_position_fk_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_adverts
    ADD CONSTRAINT job_position_fk_id FOREIGN KEY (job_position_id) REFERENCES public.job_positions(id) NOT VALID;


--
-- TOC entry 3025 (class 2606 OID 33297)
-- Name: cv_schools jobseeker_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_schools
    ADD CONSTRAINT jobseeker_id_fk FOREIGN KEY (jobseeker_id) REFERENCES public.jobseekers(user_id) NOT VALID;


--
-- TOC entry 3024 (class 2606 OID 33302)
-- Name: cv_programming_skills jobseeker_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_programming_skills
    ADD CONSTRAINT jobseeker_id_fk FOREIGN KEY (jobseeker_id) REFERENCES public.jobseekers(user_id) NOT VALID;


--
-- TOC entry 3023 (class 2606 OID 33307)
-- Name: cv_links jobseeker_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_links
    ADD CONSTRAINT jobseeker_id_fk FOREIGN KEY (jobseeker_id) REFERENCES public.jobseekers(user_id) NOT VALID;


--
-- TOC entry 3027 (class 2606 OID 33312)
-- Name: cv_images jobseeker_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_images
    ADD CONSTRAINT jobseeker_id_fk FOREIGN KEY (jobseeker_id) REFERENCES public.jobseekers(user_id) NOT VALID;


--
-- TOC entry 3022 (class 2606 OID 33317)
-- Name: cv_foreign_languages jobseeker_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_foreign_languages
    ADD CONSTRAINT jobseeker_id_fk FOREIGN KEY (jobseeker_id) REFERENCES public.jobseekers(user_id) NOT VALID;


--
-- TOC entry 3021 (class 2606 OID 33322)
-- Name: cv_experiences jobseeker_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_experiences
    ADD CONSTRAINT jobseeker_id_fk FOREIGN KEY (jobseeker_id) REFERENCES public.jobseekers(user_id) NOT VALID;


--
-- TOC entry 3026 (class 2606 OID 33327)
-- Name: cv_cover_letters jobseeker_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_cover_letters
    ADD CONSTRAINT jobseeker_id_fk FOREIGN KEY (jobseeker_id) REFERENCES public.jobseekers(user_id) NOT VALID;


--
-- TOC entry 3013 (class 2606 OID 16623)
-- Name: employers user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers
    ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;


--
-- TOC entry 3012 (class 2606 OID 16628)
-- Name: jobseekers user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobseekers
    ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;


--
-- TOC entry 3014 (class 2606 OID 16633)
-- Name: employees user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;


--
-- TOC entry 3015 (class 2606 OID 24838)
-- Name: verification_codes user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_codes
    ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES public.users(id) NOT VALID;


-- Completed on 2021-06-02 17:33:59

--
-- PostgreSQL database dump complete
--

